apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress
  namespace: personal-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - brianbargholz.ca
    - www.brianbargholz.ca
    secretName: brianbargholz-ca-tls

  rules:
  - host: brianbargholz.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personal-website-service
            port:
              number: 80

  - host: www.brianbargholz.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personal-website-service
            port:
              number: 80