apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cluster-issuer.yaml
  - jenkins-deployer.yaml

images:
  - name: brigghinwebsiteacr.azurecr.io/personal-website
    newTag: "39"