resource_group_name  = "rg-personal-website-dev"
location             = "Canada Central"
acr_name             = "brigghinwebsiteacr"
aks_name             = "aks-personal-website-dev"
uai_name             = "aks-platform-identity"
role_definition_name = "AcrPull"