apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: "*"
      helm:
        releaseName: jenkins
        valueFiles:
          - $values/k8s/jenkins/jenkins-values.yaml

    - repoURL: https://github.com/Brigghin/personal-aks-platform
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true