apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jenkins
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.9.53

      helm:
        releaseName: jenkins

        valueFiles:
          - $values/k8s/argocd/values/jenkins-values.yaml

    - repoURL: https://github.com/Brigghin/personal-aks-platform.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true