apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: jenkins

  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: jenkins-admin-user

    - secretKey: jenkins-admin-password
      remoteRef:
        key: jenkins-admin-password