apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-brigghin-dev.vault.azure.net"
      tenantId: "b597579a-4f58-4ebd-bc64-52debecb380b"

      serviceAccountRef:
        name: external-secrets