apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: personal-website-updater
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: personal-website
      useAnnotations: true