grafana:
  admin:
    existingSecret: monitoring-grafana
    userKey: admin-user
    passwordKey: admin-password

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.brianbargholz.ca

    tls:
      - secretName: grafana-brianbargholz-ca-tls
        hosts:
          - grafana.brianbargholz.ca

  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi